apiVersion: apps/v1
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'CloudModernization POC - IGD SecureInfrastructure (estimate 2K)(4240efe1-769d-4c57-aa12-02903ffdfd34)'
    azureResourceGroup: 'IGD-S9-RG'
    kubernetesCluster: 'IGD-AKS-01'
    useClusterAdmin: true
    namespace: 'default'
    command: 
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
kind: Deployment
metadata:
  name: sif-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sif-front
  template:
    metadata:
      labels:
        app: sif-front
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: sif-front
        image: igds9rgt01.azurecr.io/sif:1.1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sif-front
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: sif-front